name: CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps: 
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
      - name: Run Unit tests.
        run: make test
      - name: Run vet
        run: make vet
